CREATE TABLE artisan (
  id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
  name VARCHAR(256) NOT NULL UNIQUE ,
  email VARCHAR(256) NOT NULL UNIQUE ,
  password VARCHAR(256) NOT NULL ,
  product_id BIGINT
);